# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/proyecto ingdatos',
                'doc_host': 'https://master.github.io',
                'git_url': 'https://github.com/master/proyecto ingdatos',
                'lib_path': 'proyecto ingdatos'},
  'syms': {'proyecto ingdatos.core': {'proyecto ingdatos.core.foo': ('core.html#foo', 'proyecto ingdatos/core.py')}}}
